version: '3'
services:
  redis:
    image: redis:7.2.3-alpine3.19
    restart: always
    logging:
      driver: json-file
      options:
        max-size: '200k'
        max-file: '10'
    ports:
      - 6379:6379
  lawplayer-homework:
    image: lawplayer-homework:1.0.0
    environment:
      - DB_FILE_PATH=/var/db-prod.json
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - IMGUR_API_URL=https://api.imgur.com/
      - IMGUR_CLIENT_ID={{clientId}}
    ports:
      - 3000:3000
    depends_on:
      - redis